### ISSUE TITLE
How to send data to stinger?

### ISSUE THREAD

**Issue by Agnes007** [stingergraph/stinger#238] opened 2017-08-30 08:38 UTC
Hi, I am completely new to stinger.
problem: I have the data in JSON format, but I don't know how to use stinger to analyse the data. The README file only  points a new user to some binary examples that run on rmat generated data and how to parse csv/json file, but what to do after parsing?
Thanks so much.

**Comment by jpfairbanks** [comment] 2017-08-31 02:07
What kind of analysis are you looking for?

**Comment by Agnes007** [comment] 2017-08-31 03:05
I use STINGER as self-contained software package, and I want STINGER  analyse  data using the algorithm such as streaming comunity detection and streaming betweenness centrality. 
I had ran this example:
     term1:build$ env STINGER_MAX_MEMSIZE=1G ./bin/stinger_server
     term2:build$ ./bin/stinger_json_rpc_server
     term3:build$ ./bin/stinger_static_components
     term4:build$ ./bin/stinger_pagerank
     term5:build$ ./bin/stinger_rmat_edge_generator -n 100000 -x 10000
problem1: Resulted in http://localhost:8088/full.html, returning  Error 404: Not Found File not found. (the  path of build is .../Downloads/stinger-15.10.1/build/ , and I had already run the . ../SOURCEME.sh after building.) 
problem2: If I don't want to use the rmat_edge_generator, and I have my own data, can I replace the command in term5:build$ ./bin/stinger_rmat_edge_generator -n 100000 -x 10000 with other command to stream my own data into STINGER?

**Comment by jpfairbanks** [comment] 2017-08-31 11:31
You can use a stream such as the json stream. stinger/src/clients/streams/json_stream/src/main.cpp

**Comment by Agnes007** [comment] 2017-09-01 01:31
OK, I will try it. Thank you!

**Comment by Agnes007** [comment] 2017-09-13 06:34
I am sorry, I have another question. As I mentioned before, I cann't open  http://localhost:8088/full.html successfully, therefore, I install Apache2 and the web site can work well in local, but in other host,  I can open the web site but it cannot display dynamic graphics.  Could you give me some suggestions?

**Comment by ehein6** [comment] 2017-12-11 21:18
Is this second issue a duplicate of #239?

**Comment by Agnes007** [comment] 2017-12-12 08:31
Yes, I've already fixed it, Thank you!

**Closed as completed** 2017-12-12 13:41 UTC
